/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ExtendedInput {
    /**
    * The first name
    */
    'type': string;
  }
  interface ExtendedInputAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'type'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ExtendedInput': Components.ExtendedInput;
  }

  interface StencilIntrinsicElements {
    'extended-input': Components.ExtendedInputAttributes;
  }


  interface HTMLExtendedInputElement extends Components.ExtendedInput, HTMLStencilElement {}
  var HTMLExtendedInputElement: {
    prototype: HTMLExtendedInputElement;
    new (): HTMLExtendedInputElement;
  };

  interface HTMLElementTagNameMap {
    'extended-input': HTMLExtendedInputElement
  }

  interface ElementTagNameMap {
    'extended-input': HTMLExtendedInputElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
